/**
 * @file lib/server/notifications/payload.ts
 * EXTERNAL NOTIFICATIONS: tier enforcement -- the single place that decides what a
 * third party is allowed to learn.
 *
 * `buildPayload` is the ONLY function permitted to read `TriggerEvent.rawText`, and it
 * reads it only when the destination has been explicitly escalated to the `excerpt` tier
 * with a recorded consent timestamp. At every lower tier the raw text is never touched,
 * so the resulting payload cannot contain journal content even by accident.
 *
 * At the `excerpt` tier the text still passes through the Privacy Shield in STRICT mode
 * before truncation, and the masked categories ride along on the payload so the Egress
 * Ledger can show the user exactly what left for Slack or Discord.
 */

import { runPrivacyShield } from '@/lib/server/redaction';
import {
  MAX_EXCERPT_CHARS,
  NotificationDestination,
  NotificationPayload,
  PayloadTier,
  TriggerEvent,
} from './types';

const TRIGGER_HEADLINE: Record<string, string> = {
  entry_created: 'New journal entry',
  entry_mode: 'New journal entry',
  entry_tagged: 'New tagged journal entry',
  commitment_created: 'You stated a commitment',
  commitment_overdue: 'A commitment passed its time',
  themes_threshold: 'Recurring themes surfaced',
};

/**
 * Resolves the tier a destination may actually use.
 *
 * The `excerpt` tier is downgraded to `metadata` unless a consent timestamp is recorded.
 * This is belt-and-braces: the API refuses to set the tier without consent in the first
 * place, but a record edited by any other path still cannot leak content.
 */
export function effectiveTier(destination: NotificationDestination): PayloadTier {
  if (destination.payloadTier === 'excerpt' && !destination.excerptConsentAt) {
    return 'metadata';
  }
  return destination.payloadTier;
}

/** Truncates on a word boundary so an excerpt never ends mid-word. */
function truncate(text: string, max: number): string {
  const collapsed = text.replace(/\s+/g, ' ').trim();
  if (collapsed.length <= max) return collapsed;
  const cut = collapsed.slice(0, max);
  const lastSpace = cut.lastIndexOf(' ');
  return `${(lastSpace > max * 0.6 ? cut.slice(0, lastSpace) : cut).trimEnd()}…`;
}

/**
 * Builds the outbound payload for one destination.
 *
 * Note the structure: `rawText` is referenced exactly once, inside the `excerpt` branch.
 * Everything above that point is derived from counts, enum values, and tags the user
 * typed themselves.
 */
export function buildPayload(
  destination: NotificationDestination,
  event: TriggerEvent,
  appUrl: string
): NotificationPayload {
  const tier = effectiveTier(destination);
  const base = appUrl.replace(/\/+$/, '');
  const deepLink = `${base}/?entry=${encodeURIComponent(event.entryId)}`;

  // ---- Tier: signal -------------------------------------------------------
  // Says only that something happened. No trigger name, no mode, no tags: even a
  // trigger name like "entry_tagged: therapy" would disclose something.
  if (tier === 'signal') {
    return {
      tier,
      title: 'Journal activity',
      lines: ['Something you set up a notification for happened in your journal.'],
      deepLink,
      redactedCategories: [],
    };
  }

  // ---- Tier: metadata -----------------------------------------------------
  // Adds structure the user themselves authored or selected, plus counts.
  // Still contains no free text written by the user or generated by the model.
  const lines: string[] = [];
  const headline = TRIGGER_HEADLINE[event.type] ?? 'Journal activity';

  if (event.mode) lines.push(`Mode: ${event.mode}`);
  if (event.tags && event.tags.length > 0) {
    lines.push(`Tags: ${event.tags.slice(0, 8).join(', ')}`);
  }
  if (typeof event.commitmentCount === 'number' && event.commitmentCount > 0) {
    lines.push(
      `${event.commitmentCount} commitment${event.commitmentCount === 1 ? '' : 's'} involved`
    );
  }
  if (typeof event.themeCount === 'number' && event.themeCount > 0) {
    lines.push(`${event.themeCount} recurring theme${event.themeCount === 1 ? '' : 's'}`);
  }
  if (lines.length === 0) lines.push('No further detail at this notification level.');

  if (tier === 'metadata') {
    return { tier, title: headline, lines, deepLink, redactedCategories: [] };
  }

  // ---- Tier: excerpt ------------------------------------------------------
  // The only branch that touches journal text, and only after strict redaction.
  const raw = typeof event.rawText === 'string' ? event.rawText : '';
  if (!raw.trim()) {
    return { tier, title: headline, lines, deepLink, redactedCategories: [] };
  }

  const shielded = runPrivacyShield(raw, 'strict');
  const excerpt = truncate(shielded.redactedText, MAX_EXCERPT_CHARS);

  return {
    tier,
    title: headline,
    lines: [...lines, '', excerpt],
    deepLink,
    redactedCategories: Object.keys(shielded.categoryCounts),
  };
}
